name: Configure GitHub Pages
on:
  pull_request:
    branches:
    - main
jobs:
  build-deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/configure-pages@v3.0.6
        with:
          # GitHub token
          token: ${{ github.token }}
          # Try to enable Pages for the repository if it is not already enabled. This option requires a token other than `GITHUB_TOKEN` to be provided. In the context of a Personal Access Token, the `repo` scope or Pages write permission is required. In the context of a GitHub App, the `administration:write` and `pages:write` permissions are required.
          # enablement: # optional, default is false
